version: '3.4'

services:
  projectharbor.webclient:
    container_name: projectharbor.webclient
    build:
      context: clients/ProjectHarbor.WebClient
      dockerfile: Dockerfile.Development
    depends_on:
      - projectharbor.apigateway

  projectharbor.apigateway:
    container_name: projectharbor.apigateway
    image: ${DOCKER_REGISTRY-}projectharborapigateway
    build:
      context: .
      dockerfile: gateway/ProjectHarbor.ApiGateway/Dockerfile
    depends_on:
      - projectharbor.projects

  projectharbor.identity:
    container_name: projectharbor.identity
    image: ${DOCKER_REGISTRY-}projectharboridentitywebapi
    build:
      context: .
      dockerfile: services/ProjectHarbor.Identity/ProjectHarbor.Identity.WebApi/Dockerfile

  projectharbor.projects:
    container_name: projectharbor.projects
    image: ${DOCKER_REGISTRY-}projectharbor-projects
    build:
      context: .
      dockerfile: services/ProjectHarbor.Projects/ProjectHarbor.Projects.WebApi/Dockerfile
    depends_on:
      - projectharbor.database

  projectharbor.database:
    container_name: projectharbor.database
    image: mcr.microsoft.com/mssql/server:2022-latest

